devfreq: bwmon: Export symbols
Export symbols to fix the following modpost errors:

  ERROR: "bw_hwmon_sample_end" [drivers/devfreq/bimc-bwmon.ko] undefined!
  ERROR: "register_bw_hwmon" [drivers/devfreq/bimc-bwmon.ko] undefined!
  ERROR: "update_bw_hwmon" [drivers/devfreq/bimc-bwmon.ko] undefined!

Change-Id: Ic0dedbad2f49e98b415a2ded471b2c35b97157a8
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
(cherry picked from commit da395a639ec55c9c2cfbd126680dc62eaa722b9e)