PM / devfreq: memlat: Export symbols
Fix the following modpost errors:

  ERROR: "register_memlat" [drivers/devfreq/arm-memlat-mon.ko] undefined!
  ERROR: "register_compute" [drivers/devfreq/arm-memlat-mon.ko] undefined!

Change-Id: Ic0dedbadbcf146483ec6810e11b8a2e82e399ebd
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
(cherry picked from commit 8066226718990975095125c4d59308a04c0ca3f8)